services:
  web:
    container_name: taimu-web
    build:
      context: .
    command: uvicorn src.main:app --host 0.0.0.0 --port ${WEB_CONTAINER_PORT}
    volumes:
      - ./src:/opt/taimu/src
    ports:
      - "${WEB_HOST_PORT}:${WEB_CONTAINER_PORT}"
    restart: unless-stopped
    env_file:
      - .env
  db:
    container_name: taimu-db
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
    expose:
      - "${POSTGRES_CONTAINER_PORT}"

volumes:
  postgres_data:
